---
- name: Activity2 - install php
  become: yes
  hosts: all
  tasks:
    - name: install apche and php
      ansible.builtin.apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
        update_cache: yes
        state: present
    - name: copy content
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php