---
- name: install apache and php
  hosts: all
  become: yes
  tasks:
    - name: install apache
      ansible.builtin.dnf:
        name: 
          - httpd
          - php 
          - php-cli 
          - php-common
        state: present
    - name: create info.php
      ansible.builtin.copy:
        content: '<?phpphpinfo();?>'
        dest: /var/www/html/info.php