---
- name: Activity5 install Tomcat 10
  hosts: appservers
  become: yes 
  vars:
    username: tomcat
    group_name: tomcat
    home_directory: /opt/tomcat
    shelltype: /bin/false
    java_version: "11"
  tasks:
    - name: install jdk
      ansible.builtin.apt:
        name: "openjdk-{{  java_version  }}-jdk"
        update_cache: yes
        state: present
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create Tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ group_name }}"
        home: "{{ home_directory }}"
        create_home: true
        shell: "{{ shelltype }}"
