---
- name: Activity5 install Tomcat 10
  hosts: appservers
  become: yes 
  vars:
    username: tomcat
    group_name: tomcat
    home_directory: /opt/tomcat
    shelltype: /bin/false
    java_version: "11"
    tomcat_major_version: 10
    tomcat_specific_version: 10.1.14
  tasks:
    - name: Fail on other OS except ubuntu
      ansible_builtin.fail:
        msg: "Works only on Debian based OS"
      when: ansible_facts["os_family"] != "Debian"
    - name: install jdk
      ansible.builtin.apt:
        name: "openjdk-{{  java_version  }}-jdk"
        update_cache: yes
        state: present
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create Tomcat user
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ group_name }}"
        home: "{{ home_directory }}"
        create_home: true
        shell: "{{ shelltype }}"
    - name: donwload tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_specific_version }}/bin/apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_specific_version }}.tar.gz"
